#ifndef FRT_INTERNAL_H
#define FRT_INTERNAL_H

/* Constants */
#define ENGLISH_STOP_WORDS          FRT_ENGLISH_STOP_WORDS
#define EXCEPT_H                    FRT_EXCEPT_H
#define EXTENDED_ENGLISH_STOP_WORDS FRT_EXTENDED_ENGLISH_STOP_WORDS
#define FULL_DANISH_STOP_WORDS      FRT_FULL_DANISH_STOP_WORDS
#define FULL_DUTCH_STOP_WORDS       FRT_FULL_DUTCH_STOP_WORDS
#define FULL_ENGLISH_STOP_WORDS     FRT_FULL_ENGLISH_STOP_WORDS
#define FULL_FINNISH_STOP_WORDS     FRT_FULL_FINNISH_STOP_WORDS
#define FULL_FRENCH_STOP_WORDS      FRT_FULL_FRENCH_STOP_WORDS
#define FULL_GERMAN_STOP_WORDS      FRT_FULL_GERMAN_STOP_WORDS
#define FULL_HUNGARIAN_STOP_WORDS   FRT_FULL_HUNGARIAN_STOP_WORDS
#define FULL_ITALIAN_STOP_WORDS     FRT_FULL_ITALIAN_STOP_WORDS
#define FULL_NORWEGIAN_STOP_WORDS   FRT_FULL_NORWEGIAN_STOP_WORDS
#define FULL_PORTUGUESE_STOP_WORDS  FRT_FULL_PORTUGUESE_STOP_WORDS
#define FULL_RUSSIAN_STOP_WORDS     FRT_FULL_RUSSIAN_STOP_WORDS
#define FULL_SPANISH_STOP_WORDS     FRT_FULL_SPANISH_STOP_WORDS
#define FULL_SWEDISH_STOP_WORDS     FRT_FULL_SWEDISH_STOP_WORDS
#define HASH_MINSIZE                FRT_HASH_MINSIZE
#define HAS_GNUC_VARARGS            FRT_HAS_GNUC_VARARGS
#define HAS_ISO_VARARGS             FRT_HAS_ISO_VARARGS
#define HAS_VARARGS                 FRT_HAS_VARARGS
#define HS_MIN_SIZE                 FRT_HS_MIN_SIZE
#define IS_C                        FRT_IS_C
#define PQ_ADDED                    FRT_PQ_ADDED
#define PQ_DROPPED                  FRT_PQ_DROPPED
#define PQ_INSERTED                 FRT_PQ_INSERTED
#define SLOW_DOWN                   FRT_SLOW_DOWN
#define VEXIT                       FRT_VEXIT
#define WIN                         FRT_WIN
#define XEXIT                       FRT_XEXIT

/* Types */
#define Analyzer                FerretAnalyzer
#define CachedTokenStream       FerretCachedTokenStream
#define HashEntry               FerretHashEntry
#define HashKeyStatus           FerretHashKeyStatus
#define HashSet                 FerretHashSet
#define HashSetEntry            FerretHashSetEntry
#define HashTable               FerretHashTable
#define HyphenFilter            FerretHyphenFilter
#define MappingFilter           FerretMappingFilter
#define MultiByteTokenStream    FerretMultiByteTokenStream
#define PerFieldAnalyzer        FerretPerFieldAnalyzer
#define PriorityQueue           FerretPriorityQueue
#define PriorityQueueInsertEnum FerretPriorityQueueInsertEnum
#define StandardTokenizer       FerretStandardTokenizer
#define StemFilter              FerretStemFilter
#define StopFilter              FerretStopFilter
#define Token                   FerretToken
#define TokenFilter             FerretTokenFilter
#define TokenStream             FerretTokenStream

/* Functions */
#define a_deref                                 frt_a_deref
#define a_get_ts                                frt_a_get_ts
#define a_standard_destroy                      frt_a_standard_destroy
#define analyzer_new                            frt_analyzer_new
#define clean_up                                frt_clean_up
#define ecalloc                                 frt_ecalloc
#define emalloc                                 frt_emalloc
#define eq_ft                                   frt_eq_ft
#define erealloc                                frt_erealloc
#define filter_clone_size                       frt_filter_clone_size
#define free_ft                                 frt_free_ft
#define h_clear                                 frt_h_clear
#define h_clone                                 frt_h_clone
#define h_clone_func_t                          frt_h_clone_func_t
#define h_del                                   frt_h_del
#define h_del_int                               frt_h_del_int
#define h_destroy                               frt_h_destroy
#define h_each                                  frt_h_each
#define h_each_key_val_ft                       frt_h_each_key_val_ft
#define h_get                                   frt_h_get
#define h_get_int                               frt_h_get_int
#define h_has_key                               frt_h_has_key
#define h_has_key_int                           frt_h_has_key_int
#define h_lookup                                frt_h_lookup
#define h_lookup_ft                             frt_h_lookup_ft
#define h_new                                   frt_h_new
#define h_new_int                               frt_h_new_int
#define h_new_str                               frt_h_new_str
#define h_rem                                   frt_h_rem
#define h_rem_int                               frt_h_rem_int
#define h_set                                   frt_h_set
#define h_set_ext                               frt_h_set_ext
#define h_set_int                               frt_h_set_int
#define h_set_safe                              frt_h_set_safe
#define h_set_safe_int                          frt_h_set_safe_int
#define h_str_print_keys                        frt_h_str_print_keys
#define hash_ft                                 frt_hash_ft
#define hs_add                                  frt_hs_add
#define hs_add_safe                             frt_hs_add_safe
#define hs_clear                                frt_hs_clear
#define hs_del                                  frt_hs_del
#define hs_destroy                              frt_hs_destroy
#define hs_exists                               frt_hs_exists
#define hs_free                                 frt_hs_free
#define hs_merge                                frt_hs_merge
#define hs_new                                  frt_hs_new
#define hs_new_str                              frt_hs_new_str
#define hs_orig                                 frt_hs_orig
#define hs_rem                                  frt_hs_rem
#define hyphen_filter_new                       frt_hyphen_filter_new
#define init                                    frt_init
#define letter_analyzer_new                     frt_letter_analyzer_new
#define letter_tokenizer_new                    frt_letter_tokenizer_new
#define lowercase_filter_new                    frt_lowercase_filter_new
#define lt_ft                                   frt_lt_ft
#define mapping_filter_add                      frt_mapping_filter_add
#define mapping_filter_new                      frt_mapping_filter_new
#define mb_letter_analyzer_new                  frt_mb_letter_analyzer_new
#define mb_letter_tokenizer_new                 frt_mb_letter_tokenizer_new
#define mb_lowercase_filter_new                 frt_mb_lowercase_filter_new
#define mb_standard_analyzer_new                frt_mb_standard_analyzer_new
#define mb_standard_analyzer_new_with_words     frt_mb_standard_analyzer_new_with_words
#define mb_standard_analyzer_new_with_words_len frt_mb_standard_analyzer_new_with_words_len
#define mb_standard_tokenizer_new               frt_mb_standard_tokenizer_new
#define mb_whitespace_analyzer_new              frt_mb_whitespace_analyzer_new
#define mb_whitespace_tokenizer_new             frt_mb_whitespace_tokenizer_new
#define micro_sleep                             frt_micro_sleep
#define non_analyzer_new                        frt_non_analyzer_new
#define non_tokenizer_new                       frt_non_tokenizer_new
#define per_field_analyzer_new                  frt_per_field_analyzer_new
#define pfa_add_field                           frt_pfa_add_field
#define pq_clear                                frt_pq_clear
#define pq_clone                                frt_pq_clone
#define pq_destroy                              frt_pq_destroy
#define pq_down                                 frt_pq_down
#define pq_free                                 frt_pq_free
#define pq_full                                 frt_pq_full
#define pq_insert                               frt_pq_insert
#define pq_new                                  frt_pq_new
#define pq_pop                                  frt_pq_pop
#define pq_push                                 frt_pq_push
#define pq_top                                  frt_pq_top
#define progname                                frt_progname
#define ptr_eq                                  frt_ptr_eq
#define ptr_hash                                frt_ptr_hash
#define setprogname                             frt_setprogname
#define standard_analyzer_new                   frt_standard_analyzer_new
#define standard_analyzer_new_with_words        frt_standard_analyzer_new_with_words
#define standard_analyzer_new_with_words_len    frt_standard_analyzer_new_with_words_len
#define standard_tokenizer_new                  frt_standard_tokenizer_new
#define stem_filter_new                         frt_stem_filter_new
#define stop_filter_new                         frt_stop_filter_new
#define stop_filter_new_with_words              frt_stop_filter_new_with_words
#define stop_filter_new_with_words_len          frt_stop_filter_new_with_words_len
#define str_hash                                frt_str_hash
#define tf_new_i                                frt_tf_new_i
#define tk_cmp                                  frt_tk_cmp
#define tk_destroy                              frt_tk_destroy
#define tk_eq                                   frt_tk_eq
#define tk_new                                  frt_tk_new
#define tk_set                                  frt_tk_set
#define tk_set_no_len                           frt_tk_set_no_len
#define ts_clone                                frt_ts_clone
#define ts_clone_size                           frt_ts_clone_size
#define ts_deref                                frt_ts_deref
#define ts_new                                  frt_ts_new
#define ts_new_i                                frt_ts_new_i
#define ts_next                                 frt_ts_next
#define vexit                                   frt_vexit
#define whitespace_analyzer_new                 frt_whitespace_analyzer_new
#define whitespace_tokenizer_new                frt_whitespace_tokenizer_new
#define xexit                                   frt_xexit

#endif
