#ifndef FRT_INTERNAL_H
#define FRT_INTERNAL_H

/* Constants */
#define ABS                         FRT_ABS
#define ALLOC                       FRT_ALLOC
#define ALLOC_AND_ZERO              FRT_ALLOC_AND_ZERO
#define ALLOC_AND_ZERO_N            FRT_ALLOC_AND_ZERO_N
#define ALLOC_N                     FRT_ALLOC_N
#define ARY_INIT_CAPA               FRT_ARY_INIT_CAPA
#define ARY_META_CNT                FRT_ARY_META_CNT
#define BV_INIT_CAPA                FRT_BV_INIT_CAPA
#define DEREF                       FRT_DEREF
#define EMPTY_STRING                FRT_EMPTY_STRING
#define ENGLISH_STOP_WORDS          FRT_ENGLISH_STOP_WORDS
#define EXCEPT_H                    FRT_EXCEPT_H
#define EXTENDED_ENGLISH_STOP_WORDS FRT_EXTENDED_ENGLISH_STOP_WORDS
#define FULL_DANISH_STOP_WORDS      FRT_FULL_DANISH_STOP_WORDS
#define FULL_DUTCH_STOP_WORDS       FRT_FULL_DUTCH_STOP_WORDS
#define FULL_ENGLISH_STOP_WORDS     FRT_FULL_ENGLISH_STOP_WORDS
#define FULL_FINNISH_STOP_WORDS     FRT_FULL_FINNISH_STOP_WORDS
#define FULL_FRENCH_STOP_WORDS      FRT_FULL_FRENCH_STOP_WORDS
#define FULL_GERMAN_STOP_WORDS      FRT_FULL_GERMAN_STOP_WORDS
#define FULL_HUNGARIAN_STOP_WORDS   FRT_FULL_HUNGARIAN_STOP_WORDS
#define FULL_ITALIAN_STOP_WORDS     FRT_FULL_ITALIAN_STOP_WORDS
#define FULL_NORWEGIAN_STOP_WORDS   FRT_FULL_NORWEGIAN_STOP_WORDS
#define FULL_PORTUGUESE_STOP_WORDS  FRT_FULL_PORTUGUESE_STOP_WORDS
#define FULL_RUSSIAN_STOP_WORDS     FRT_FULL_RUSSIAN_STOP_WORDS
#define FULL_SPANISH_STOP_WORDS     FRT_FULL_SPANISH_STOP_WORDS
#define FULL_SWEDISH_STOP_WORDS     FRT_FULL_SWEDISH_STOP_WORDS
#define HASH_MINSIZE                FRT_HASH_MINSIZE
#define HAS_GNUC_VARARGS            FRT_HAS_GNUC_VARARGS
#define HAS_ISO_VARARGS             FRT_HAS_ISO_VARARGS
#define HAS_VARARGS                 FRT_HAS_VARARGS
#define HS_MIN_SIZE                 FRT_HS_MIN_SIZE
#define INLINE                      FRT_INLINE
#define IS_C99                      FRT_IS_C99
#define MAX                         FRT_MAX
#define MAX3                        FRT_MAX3
#define MAX_FILE_PATH               FRT_MAX_FILE_PATH
#define MAX_WORD_SIZE               FRT_MAX_WORD_SIZE
#define MIN                         FRT_MIN
#define MIN3                        FRT_MIN3
#define NELEMS                      FRT_NELEMS
#define NEXT_NUM                    FRT_NEXT_NUM
#define OFF_T_PFX                   FRT_OFF_T_PFX
#define PQ_ADDED                    FRT_PQ_ADDED
#define PQ_DROPPED                  FRT_PQ_DROPPED
#define PQ_INSERTED                 FRT_PQ_INSERTED
#define PREV_NUM                    FRT_PREV_NUM
#define REALLOC_N                   FRT_REALLOC_N
#define RECAPA                      FRT_RECAPA
#define REF                         FRT_REF
#define SLOW_DOWN                   FRT_SLOW_DOWN
#define VEXIT                       FRT_VEXIT
#define WIN32_H                     FRT_WIN32_H
#define XEXIT                       FRT_XEXIT
#define ZEROSET                     FRT_ZEROSET
#define ZEROSET_N                   FRT_ZEROSET_N

/* Types */
#define Analyzer                FrtAnalyzer
#define BitVector               FrtBitVector
#define CachedTokenStream       FrtCachedTokenStream
#define HashEntry               FrtHashEntry
#define HashKeyStatus           FrtHashKeyStatus
#define HashSet                 FrtHashSet
#define HashSetEntry            FrtHashSetEntry
#define HashTable               FrtHashTable
#define HyphenFilter            FrtHyphenFilter
#define MappingFilter           FrtMappingFilter
#define MultiByteTokenStream    FrtMultiByteTokenStream
#define PerFieldAnalyzer        FrtPerFieldAnalyzer
#define PriorityQueue           FrtPriorityQueue
#define PriorityQueueInsertEnum FrtPriorityQueueInsertEnum
#define StandardTokenizer       FrtStandardTokenizer
#define StemFilter              FrtStemFilter
#define StopFilter              FrtStopFilter
#define Token                   FrtToken
#define TokenFilter             FrtTokenFilter
#define TokenStream             FrtTokenStream

/* Functions */
#define a_deref                                 frt_a_deref
#define a_get_ts                                frt_a_get_ts
#define a_standard_destroy                      frt_a_standard_destroy
#define analyzer_new                            frt_analyzer_new
#define ary_capa                                frt_ary_capa
#define ary_delete                              frt_ary_delete
#define ary_delete_i                            frt_ary_delete_i
#define ary_destroy                             frt_ary_destroy
#define ary_destroy_i                           frt_ary_destroy_i
#define ary_each                                frt_ary_each
#define ary_each_rev                            frt_ary_each_rev
#define ary_free                                frt_ary_free
#define ary_get                                 frt_ary_get
#define ary_get_i                               frt_ary_get_i
#define ary_grow                                frt_ary_grow
#define ary_last                                frt_ary_last
#define ary_new                                 frt_ary_new
#define ary_new_capa                            frt_ary_new_capa
#define ary_new_i                               frt_ary_new_i
#define ary_new_type                            frt_ary_new_type
#define ary_new_type_capa                       frt_ary_new_type_capa
#define ary_pop                                 frt_ary_pop
#define ary_pop_i                               frt_ary_pop_i
#define ary_push                                frt_ary_push
#define ary_push_i                              frt_ary_push_i
#define ary_remove                              frt_ary_remove
#define ary_remove_i                            frt_ary_remove_i
#define ary_resize                              frt_ary_resize
#define ary_resize_i                            frt_ary_resize_i
#define ary_rsz                                 frt_ary_rsz
#define ary_set                                 frt_ary_set
#define ary_set_i                               frt_ary_set_i
#define ary_shift                               frt_ary_shift
#define ary_shift_i                             frt_ary_shift_i
#define ary_size                                frt_ary_size
#define ary_sort                                frt_ary_sort
#define ary_start                               frt_ary_start
#define ary_sz                                  frt_ary_sz
#define ary_type_size                           frt_ary_type_size
#define ary_unshift                             frt_ary_unshift
#define ary_unshift_i                           frt_ary_unshift_i
#define bv_and                                  frt_bv_and
#define bv_and_x                                frt_bv_and_x
#define bv_clear                                frt_bv_clear
#define bv_destroy                              frt_bv_destroy
#define bv_eq                                   frt_bv_eq
#define bv_get                                  frt_bv_get
#define bv_hash                                 frt_bv_hash
#define bv_new                                  frt_bv_new
#define bv_new_capa                             frt_bv_new_capa
#define bv_not                                  frt_bv_not
#define bv_not_x                                frt_bv_not_x
#define bv_or                                   frt_bv_or
#define bv_or_x                                 frt_bv_or_x
#define bv_recount                              frt_bv_recount
#define bv_scan_next                            frt_bv_scan_next
#define bv_scan_next_from                       frt_bv_scan_next_from
#define bv_scan_next_unset                      frt_bv_scan_next_unset
#define bv_scan_next_unset_from                 frt_bv_scan_next_unset_from
#define bv_scan_reset                           frt_bv_scan_reset
#define bv_set                                  frt_bv_set
#define bv_set_fast                             frt_bv_set_fast
#define bv_unset                                frt_bv_unset
#define bv_xor                                  frt_bv_xor
#define bv_xor_x                                frt_bv_xor_x
#define clean_up                                frt_clean_up
#define dbl_to_s                                frt_dbl_to_s
#define do_clean_up                             frt_do_clean_up
#define dummy_free                              frt_dummy_free
#define ecalloc                                 frt_ecalloc
#define emalloc                                 frt_emalloc
#define epstrdup                                frt_epstrdup
#define eq_ft                                   frt_eq_ft
#define erealloc                                frt_erealloc
#define estrcat                                 frt_estrcat
#define estrdup                                 frt_estrdup
#define filter_clone_size                       frt_filter_clone_size
#define free_ft                                 frt_free_ft
#define get_stacktrace                          frt_get_stacktrace
#define h_clear                                 frt_h_clear
#define h_clone                                 frt_h_clone
#define h_clone_func_t                          frt_h_clone_func_t
#define h_del                                   frt_h_del
#define h_del_int                               frt_h_del_int
#define h_destroy                               frt_h_destroy
#define h_each                                  frt_h_each
#define h_each_key_val_ft                       frt_h_each_key_val_ft
#define h_get                                   frt_h_get
#define h_get_int                               frt_h_get_int
#define h_has_key                               frt_h_has_key
#define h_has_key_int                           frt_h_has_key_int
#define h_lookup                                frt_h_lookup
#define h_lookup_ft                             frt_h_lookup_ft
#define h_new                                   frt_h_new
#define h_new_int                               frt_h_new_int
#define h_new_str                               frt_h_new_str
#define h_rem                                   frt_h_rem
#define h_rem_int                               frt_h_rem_int
#define h_set                                   frt_h_set
#define h_set_ext                               frt_h_set_ext
#define h_set_int                               frt_h_set_int
#define h_set_safe                              frt_h_set_safe
#define h_set_safe_int                          frt_h_set_safe_int
#define h_str_print_keys                        frt_h_str_print_keys
#define hash_ft                                 frt_hash_ft
#define hs_add                                  frt_hs_add
#define hs_add_safe                             frt_hs_add_safe
#define hs_clear                                frt_hs_clear
#define hs_del                                  frt_hs_del
#define hs_destroy                              frt_hs_destroy
#define hs_exists                               frt_hs_exists
#define hs_free                                 frt_hs_free
#define hs_merge                                frt_hs_merge
#define hs_new                                  frt_hs_new
#define hs_new_str                              frt_hs_new_str
#define hs_orig                                 frt_hs_orig
#define hs_rem                                  frt_hs_rem
#define hyphen_filter_new                       frt_hyphen_filter_new
#define i16                                     frt_i16
#define i32                                     frt_i32
#define i64                                     frt_i64
#define icmp                                    frt_icmp
#define icmp_risky                              frt_icmp_risky
#define imalloc                                 frt_imalloc
#define init                                    frt_init
#define letter_analyzer_new                     frt_letter_analyzer_new
#define letter_tokenizer_new                    frt_letter_tokenizer_new
#define lmalloc                                 frt_lmalloc
#define lowercase_filter_new                    frt_lowercase_filter_new
#define lt_ft                                   frt_lt_ft
#define mapping_filter_add                      frt_mapping_filter_add
#define mapping_filter_new                      frt_mapping_filter_new
#define max2                                    frt_max2
#define max3                                    frt_max3
#define mb_letter_analyzer_new                  frt_mb_letter_analyzer_new
#define mb_letter_tokenizer_new                 frt_mb_letter_tokenizer_new
#define mb_lowercase_filter_new                 frt_mb_lowercase_filter_new
#define mb_standard_analyzer_new                frt_mb_standard_analyzer_new
#define mb_standard_analyzer_new_with_words     frt_mb_standard_analyzer_new_with_words
#define mb_standard_analyzer_new_with_words_len frt_mb_standard_analyzer_new_with_words_len
#define mb_standard_tokenizer_new               frt_mb_standard_tokenizer_new
#define mb_whitespace_analyzer_new              frt_mb_whitespace_analyzer_new
#define mb_whitespace_tokenizer_new             frt_mb_whitespace_tokenizer_new
#define micro_sleep                             frt_micro_sleep
#define min2                                    frt_min2
#define min3                                    frt_min3
#define non_analyzer_new                        frt_non_analyzer_new
#define non_tokenizer_new                       frt_non_tokenizer_new
#define per_field_analyzer_new                  frt_per_field_analyzer_new
#define pfa_add_field                           frt_pfa_add_field
#define pq_clear                                frt_pq_clear
#define pq_clone                                frt_pq_clone
#define pq_destroy                              frt_pq_destroy
#define pq_down                                 frt_pq_down
#define pq_free                                 frt_pq_free
#define pq_full                                 frt_pq_full
#define pq_insert                               frt_pq_insert
#define pq_new                                  frt_pq_new
#define pq_pop                                  frt_pq_pop
#define pq_push                                 frt_pq_push
#define pq_top                                  frt_pq_top
#define print_stacktrace                        frt_print_stacktrace
#define progname                                frt_progname
#define ptr_eq                                  frt_ptr_eq
#define ptr_hash                                frt_ptr_hash
#define register_for_cleanup                    frt_register_for_cleanup
#define scmp                                    frt_scmp
#define setprogname                             frt_setprogname
#define standard_analyzer_new                   frt_standard_analyzer_new
#define standard_analyzer_new_with_words        frt_standard_analyzer_new_with_words
#define standard_analyzer_new_with_words_len    frt_standard_analyzer_new_with_words_len
#define standard_tokenizer_new                  frt_standard_tokenizer_new
#define stem_filter_new                         frt_stem_filter_new
#define stop_filter_new                         frt_stop_filter_new
#define stop_filter_new_with_words              frt_stop_filter_new_with_words
#define stop_filter_new_with_words_len          frt_stop_filter_new_with_words_len
#define str_hash                                frt_str_hash
#define strfmt                                  frt_strfmt
#define tf_new_i                                frt_tf_new_i
#define tk_cmp                                  frt_tk_cmp
#define tk_destroy                              frt_tk_destroy
#define tk_eq                                   frt_tk_eq
#define tk_new                                  frt_tk_new
#define tk_set                                  frt_tk_set
#define tk_set_no_len                           frt_tk_set_no_len
#define ts_clone                                frt_ts_clone
#define ts_clone_size                           frt_ts_clone_size
#define ts_deref                                frt_ts_deref
#define ts_new                                  frt_ts_new
#define ts_new_i                                frt_ts_new_i
#define ts_next                                 frt_ts_next
#define u16                                     frt_u16
#define u32                                     frt_u32
#define u32malloc                               frt_u32malloc
#define u64                                     frt_u64
#define u64malloc                               frt_u64malloc
#define uchar                                   frt_uchar
#define vexit                                   frt_vexit
#define vstrfmt                                 frt_vstrfmt
#define weprintf                                frt_weprintf
#define whitespace_analyzer_new                 frt_whitespace_analyzer_new
#define whitespace_tokenizer_new                frt_whitespace_tokenizer_new
#define x_abort_on_exception                    frt_x_abort_on_exception
#define x_do_logging                            frt_x_do_logging
#define x_exception_stream                      frt_x_exception_stream
#define x_has_aborted                           frt_x_has_aborted
#define xexit                                   frt_xexit

#endif
