#!/usr/bin/env ruby

require 'open-uri'  

def for_each_line(url, property)
  open(url) do |file|
    file.each_line do |line|
      next if line =~ /^#/;
      next if line !~ /; #{property} #/;

      token, description = line.split(/;/)
      token.strip!
      description.gsub!(/.*#/, '')
      description.strip!

      yield token, description
    end
  end
end

CHART = "http://www.unicode.org/Public/5.1.0/ucd/DerivedCoreProperties.txt"

puts <<EOF
# The following Ragel file is autogenerated from:
# #{CHART}
%%{
    walpha = 
EOF

pipe = " "
for_each_line( CHART, "Alphabetic" ) do |token, description|
  token = '0x' + token
  token.sub! '..', '..0x'
  dots = description.size > 47 ? "..." : "   "
  puts "      #{pipe} #{'%-18s' % token} ##{description.slice(0..47)}#{dots}"
  pipe = "|"
end

puts <<EOF
      ;

    wdigit = '0'..'9';
    walnum = walpha | wdigit;
}%%
EOF
